version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fuurin2_web
    ports:
      - "3000:3000"
    environment:
      # SvelteKit uses PORT env if provided; keeping defaults is fine
      - NODE_ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:3000').then(r=>{if(!r.ok)process.exit(1)}).catch(()=>process.exit(1))" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
